# Generated by Django 4.2 on 2023-04-15 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "docUserName",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="unknown", max_length=50)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=16)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=200)),
                ("degree", models.CharField(default="none", max_length=200)),
                ("specialization", models.CharField(default="none", max_length=200)),
                ("experience", models.IntegerField()),
                ("AccountCreatedOn", models.DateTimeField()),
                ("updatedOn", models.DateTimeField()),
            ],
            options={
                "ordering": ["-AccountCreatedOn"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patUserName",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="unknown", max_length=50)),
                ("mobile", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=16)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(max_length=10)),
                ("AccountCreatedOn", models.DateTimeField()),
            ],
            options={
                "ordering": ["-AccountCreatedOn"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disease", models.CharField(max_length=500)),
                ("bloodGroup", models.CharField(blank=True, max_length=5, null=True)),
                ("appointmentDate", models.DateField(max_length=10)),
                ("appointmentTime", models.TimeField(max_length=10)),
                ("formFilled", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField()),
                (
                    "docUserName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.doctor"
                    ),
                ),
                (
                    "patUserName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.patient"
                    ),
                ),
            ],
        ),
    ]
